name = "vtol-vr-hub"
type = "javascript"
main = "index.html"
compatibility_date = "2024-04-01"

[env.production]
vars = { ENVIRONMENT = "production" }

[[build.upload.rules]]
type = "CompiledContentType"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.{txt,html,css,js,svg,json}"]
fallthrough = true

[build]
command = ""
cwd = ""
watch_paths = []

[[build.upload.rules]]
type = "AssetType"
globs = ["**/*.{html,css,js,png,jpg,jpeg,gif,svg,ico,json}"]
fallthrough = true
